### ISSUE TITLE
想问下po主笔记是直接在github上写的吗？还是用别的软件写了复制进来的？

### ISSUE THREAD

**Issue by BetterBam** [hjzCy/sql_node#1]
感觉直接在github上写很难弄格式￣□￣｜｜

**Comment by xushijie10086** [comment]
> 感觉直接在github上写很难弄格式￣□￣｜｜
markdown

**Comment by baagod** [comment]
@BetterBam 
这是 markdown 语法。不是 github 特有的，但 github 也支持 markdown 语法。
可以搜一下 markdown 语法，看一下就会了，很简单的。

**Comment by BetterBam** [comment]
> @BetterBam
> 这是 markdown 语法。不是 github 特有的，但 github 也支持 markdown 语法。
> 可以搜一下 markdown 语法，看一下就会了，很简单的。

嗯嗯好的，谢谢啦~

**Comment by BetterBam** [comment]
> > 感觉直接在github上写很难弄格式￣□￣｜｜
> > markdown

好的谢谢~
